import { test, expect, api, sql, record, unique, card, dialog, confirm, sourceTask, showPagedCard } from './fixtures';

test('Documents: create/body version, publish, archive/unarchive, table/grid and reload', async ({ page }) => {
  await page.goto('/modules/FX20'); const title = unique('document'); await page.locator('#document-title').fill(title); await page.locator('#document-type').selectOption('Note'); await page.locator('#document-editor').selectOption('Markdown'); await page.locator('#document-body').fill('# Nội dung\n<script>literal</script>');
  const rejected = page.waitForResponse(r => r.url().endsWith('/api/v1/documents') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Tạo page', exact: true }).click(); expect((await rejected).status()).toBe(422);
  await expect(page.getByRole('alert')).toContainText('Executable markup'); await expect(page.locator('#document-body')).toHaveValue('# Nội dung\n<script>literal</script>');
  await page.locator('#document-body').fill('# Nội dung\nNội dung tổng hợp.'); await page.getByRole('button', { name: 'Tạo page', exact: true }).click();
  const { item } = await record(page, 'listDocuments', [undefined, 100], 'Document', title); await page.locator('#document-body').fill('# Version two'); await page.getByRole('button', { name: 'Save version' }).click(); await expect.poll(() => sql('Document', item.id)[0].VersionNumber).toBe(2);
  await page.getByRole('button', { name: 'Publish', exact: true }).click(); await expect.poll(() => sql('Document', item.id)[0].Status).toBe('Published'); await page.getByRole('button', { name: 'Archive', exact: true }).click(); await confirm(page, 'Archive document'); await expect(page.locator('#document-body')).toBeDisabled(); expect(sql('Document', item.id)[0].Status).toBe('Archived');
  await page.getByRole('button', { name: 'Unarchive' }).click(); await expect.poll(() => sql('Document', item.id)[0].Status).toBe('Published'); await page.getByRole('tab', { name: 'Table', exact: true }).click(); await expect(page.getByRole('row').filter({ hasText: title })).toBeVisible(); await page.getByRole('tab', { name: 'Grid', exact: true }).click(); await page.reload(); await card(page, title).getByRole('button', { name: 'Mở', exact: true }).click(); await expect(page.locator('#document-body')).toHaveValue('# Version two');
});

test('Snippets: literal content, edit/version, archive/unarchive and SQL reload', async ({ page }) => {
  await page.goto('/modules/FX22'); const title = unique('snippet'); await page.locator('#snippet-title').fill(title); await page.locator('#snippet-body').fill('<script>window.qaExecuted=true</script>'); await page.getByRole('button', { name: 'Tạo snippet', exact: true }).click();
  const { item } = await record(page, 'listSnippets', [true, '', 100], 'Snippet', title); expect(await page.evaluate(() => (window as any).qaExecuted)).toBeUndefined(); expect(sql('Snippet', item.id)[0].Body).toBe('<script>window.qaExecuted=true</script>');
  await card(page, title).getByRole('button', { name: 'Sửa', exact: true }).click(); await page.locator('#snippet-body').fill('const answer = 42;'); await page.getByRole('button', { name: 'Lưu version', exact: true }).click(); await expect.poll(() => sql('Snippet', item.id)[0].Body).toBe('const answer = 42;');
  await card(page, title).getByRole('button', { name: 'Archive', exact: true }).click(); await confirm(page, 'Archive snippet'); expect(sql('Snippet', item.id)[0].Status).toBe('Archived'); await page.getByLabel('Hiển thị snippet đã archive').check(); await card(page, title).getByRole('button', { name: 'Unarchive' }).click(); await expect.poll(() => sql('Snippet', item.id)[0].Status).toBe('Active'); await page.reload(); await expect(card(page, title)).toBeVisible();
});

test('Read Later: add source, invalid/valid position, read/unread and remove preserves source', async ({ page }) => {
  await page.goto('/'); const title = unique('reading'); const source = await api(page, 'createBookmark', ['https://example.invalid/' + title, title, 'source fixture']); await page.goto('/modules/FX23'); let modal = await dialog(page, 'Thêm vào Read Later'); await page.locator('#read-later-source').selectOption(source.id); await modal.getByRole('button', { name: 'Lưu vào Read Later', exact: true }).click(); await expect(modal).toHaveCount(0);
  const { item } = await record(page, 'listReadingQueue', ['', 100], 'ReadingItem', title, 'safeTitleSnapshot'); const row = card(page, title);
  await row.getByRole('button', { name: 'Đổi vị trí' }).click(); modal = page.getByRole('dialog'); await modal.getByLabel('Position metadata (0–1)').fill('2'); await modal.getByRole('button', { name: 'Lưu vị trí' }).click(); await expect(modal.getByRole('alert')).toContainText('0 đến 1'); expect(sql('ReadingItem', item.id)[0].Progress).toBe(0);
  await modal.getByLabel('Position metadata (0–1)').fill('0.5'); await modal.getByRole('button', { name: 'Lưu vị trí' }).click(); await expect(modal).toHaveCount(0); expect(sql('ReadingItem', item.id)[0].Progress).toBe(0.5);
  await row.getByRole('button', { name: 'Đánh dấu đã đọc' }).click(); await expect.poll(() => sql('ReadingItem', item.id)[0].State).toBe('Read'); await row.getByRole('button', { name: 'Đánh dấu chưa đọc' }).click(); await expect.poll(() => sql('ReadingItem', item.id)[0].State).toBe('Unread');
  await row.getByRole('button', { name: 'Gỡ khỏi queue', exact: true }).click(); await confirm(page, 'Gỡ khỏi queue'); expect(sql('ReadingItem', item.id)).toHaveLength(0); expect(sql('Bookmark', source.id)).toHaveLength(1);
});

test('Favorites: typed reference, rank popup, server route navigation/reload and delete preserves source', async ({ page }) => {
  await page.goto('/'); const title = unique('favorite'); const source = await api(page, 'createBookmark', ['https://example.invalid/' + title, title, 'source fixture']); await page.goto('/favorites'); let modal = await dialog(page, 'Thêm favorite'); await page.locator('#favorite-resource-type').selectOption('Bookmark'); await page.locator('#favorite-resource-id').fill(source.id); await modal.getByRole('button', { name: 'Thêm favorite', exact: true }).click(); await expect(modal).toHaveCount(0);
  const { item } = await record(page, 'listFavorites', ['', 100, ''], 'Favorite', title); const row = card(page, title); await row.getByRole('button', { name: 'Đổi rank' }).click(); await page.getByRole('dialog').getByLabel('Rank', { exact: true }).fill('12.5'); await confirm(page, 'Lưu rank'); expect(sql('Favorite', item.id)[0].Rank).toBe(12.5);
  await row.getByRole('button', { name: 'Mở nguồn' }).click(); await expect(page).toHaveURL(/\/resources\/Bookmark\//); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible(); await page.goto(item.route); await page.reload(); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await page.goto('/favorites'); await card(page, title).getByRole('button', { name: 'Xóa', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Hủy', exact: true }).click(); expect(sql('Favorite', item.id)).toHaveLength(1); await card(page, title).getByRole('button', { name: 'Xóa', exact: true }).click(); await confirm(page, 'Xóa favorite'); expect(sql('Favorite', item.id)).toHaveLength(0); expect(sql('Bookmark', source.id)).toHaveLength(1);
});

test('Projects/Tasks: UI creation/edit, terminal cohort trash, restore and purge', async ({ page }) => {
  const name = unique('project'), title = unique('task'); const start = new Date(Date.now() + 86400000).toISOString().slice(0, 16), end = new Date(Date.now() + 172800000).toISOString().slice(0, 16);
  await page.goto('/modules/FX11'); await page.locator('#project-name').fill(name); await page.locator('#project-description').fill('Synthetic project'); await page.locator('#project-start').fill(start); await page.locator('#project-end').fill(end); await page.getByRole('button', { name: 'Tạo Project', exact: true }).click(); const project = (await record(page, 'listProjects', [100, ''], 'Project', name, 'name')).item;
  await page.goto('/modules/FX12'); await page.locator('#task-project').selectOption(project.id); await page.locator('#task-title').fill(title); await page.locator('#task-description').fill('Synthetic task'); await page.locator('#task-start').fill(start); await page.locator('#task-end').fill(end); await page.getByRole('button', { name: 'Tạo Task', exact: true }).click(); const task = (await record(page, 'listTasks', [project.id, 100, ''], 'Task', title)).item;
  await card(page, title).getByRole('button', { name: 'Sửa', exact: true }).click(); await page.locator('#task-status').selectOption('Completed'); await page.getByRole('button', { name: 'Lưu Task', exact: true }).click(); await expect.poll(() => sql('Task', task.id)[0].Status).toBe('Completed');
  await page.goto('/modules/FX11'); await showPagedCard(page,name,'Tải thêm Project'); await card(page, name).getByRole('button', { name: 'Hoàn tất', exact: true }).click(); await confirm(page, 'Hoàn tất Project'); await expect.poll(() => sql('Project', project.id)[0].Status).toBe('Completed');
  await card(page, name).getByRole('button', { name: 'Xóa', exact: true }).click(); await confirm(page, 'Đưa Project vào Trash'); expect(sql('Project', project.id)[0].Status).toBe('Deleted'); expect(sql('Task', task.id)[0].Status).toBe('Deleted');
  await page.goto('/trash'); let row = page.locator('.resource-card').filter({ hasText: project.id }); await row.getByRole('button', { name: 'Restore batch', exact: true }).click(); await confirm(page, 'Restore batch'); await expect.poll(() => sql('Project', project.id)[0].Status).toBe('Completed');
  // FX-08-BR-003: restoring a terminal Project leaves cohort children in Trash.
  expect(sql('Task', task.id)[0].Status).toBe('Deleted'); await page.goto('/modules/FX11'); await showPagedCard(page,name,'Tải thêm Project'); await card(page, name).getByRole('button', { name: 'Xóa', exact: true }).click(); await confirm(page, 'Đưa Project vào Trash'); await page.goto('/trash'); row = page.locator('.resource-card').filter({ hasText: project.id }); await row.getByRole('button', { name: 'Delete permanently', exact: true }).click(); await page.getByRole('dialog').getByLabel('Nhập PURGE để xóa vĩnh viễn batch').fill('PURGE'); await confirm(page, 'Delete permanently'); expect(sql('Project', project.id)).toHaveLength(0); expect(sql('Task', task.id)).toHaveLength(0);
});

test('Calendar: timed/all-day UI create/edit, views, complete/cancel and SQL state', async ({ page }) => {
  await page.goto('/modules/FX13'); const title = unique('event'), start = new Date(Date.now() + 86400000).toISOString().slice(0, 16), end = new Date(Date.now() + 172800000).toISOString().slice(0, 16);
  await page.locator('#event-title').fill(title); await page.locator('#event-description').fill('Synthetic timed event'); await page.locator('#event-start').fill(start); await page.locator('#event-end').fill(end); await page.getByRole('button', { name: 'Tạo sự kiện', exact: true }).click(); const { item } = await record(page, 'listCalendarEvents', [undefined, undefined, 100, ''], 'Event', title);
  await page.getByRole('tab', { name: 'Agenda', exact: true }).click(); await showPagedCard(page,title,'Tải thêm sự kiện'); await card(page, title).getByRole('button', { name: 'Sửa', exact: true }).click(); await page.locator('#event-title').fill(title + '-edit'); await page.getByRole('button', { name: 'Lưu sự kiện' }).click(); await expect.poll(() => sql('Event', item.id)[0].Title).toBe(title + '-edit'); await card(page, title + '-edit').getByRole('button', { name: 'Hoàn tất' }).click(); await expect.poll(() => sql('Event', item.id)[0].Status).toBe('Completed');
  await page.getByRole('button', { name: 'Làm mới', exact: true }).click(); await page.locator('#event-title').fill(title + '-all-day'); await page.locator('#event-description').fill('Synthetic all-day event'); await page.getByLabel('All-day', { exact: true }).check(); const date = start.slice(0, 10); await page.locator('#event-start').fill(date); await page.locator('#event-end').fill(date); await page.getByRole('button', { name: 'Tạo sự kiện', exact: true }).click(); const day = (await record(page, 'listCalendarEvents', [undefined, undefined, 100, ''], 'Event', title + '-all-day')).item; expect(sql('Event', day.id)[0].IsAllDay).toBe(true);
  await card(page, title + '-all-day').getByRole('button', { name: 'Hủy', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Hủy', exact: true }).click(); expect(sql('Event', day.id)[0].Status).toBe('Scheduled'); await card(page, title + '-all-day').getByRole('button', { name: 'Hủy', exact: true }).click(); await confirm(page, 'Hủy sự kiện'); expect(sql('Event', day.id)[0].Status).toBe('Canceled'); await page.reload(); await expect(card(page, title + '-all-day')).toHaveCount(0);
});
