import { test, expect, api, sql, unique, card, confirm, login } from './fixtures';
import type { Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
const account = (role: string) => JSON.parse(readFileSync(process.env.NEXORA_E2E_ACCOUNTS!, 'utf8')).find((a: any) => a.role === role);
const operator = (cmd: string, id?: string): any => JSON.parse(execFileSync(process.env.NEXORA_E2E_SQL_OPERATOR!, id ? [cmd, id] : [cmd], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }));
async function publish(page: Page, recipientUserId: string, title: string) {
  return page.evaluate(async ({recipientUserId,title}) => { const path='/src/api.ts',a=await import(path),csrf=await a.getCsrf(); const r=await fetch('/api/v1/admin/notifications',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf.requestToken,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({kind:'System',title,body:'Nội dung tổng hợp cho kiểm thử local.',sourceRef:null,logicalKey:crypto.randomUUID(),recipientUserId})}); if(r.status!==201)throw new Error('Notification prerequisite failed: '+r.status);return r.json(); },{recipientUserId,title});
}
async function selectTarget(page: Page, email: string) { await page.goto('/admin/access'); const row=page.getByRole('button').filter({has:page.getByText(email,{exact:true})}); await expect(row).toBeVisible();await row.click();await expect(page.locator('#admin-action')).toBeVisible(); }
async function setGrant(page: Page,userId: string,key: string,effect: string){const current=await api(page,'getAdminUserAccess',[userId]);if((current.actionGrants.find((g:any)=>g.actionKey===key)?.effect??'Unset')===effect)return current;const p=await api(page,'previewAdminAccess',[userId,{kind:'permissions',changes:[{actionKey:key,effect}]}]);expect(p.blockers).toHaveLength(0);return api(page,'commitAdminActionGrant',[userId,p.etag,[{actionKey:key,effect}],p.previewToken]);}
async function setModules(page: Page,userId: string,moduleId: string,enabled: boolean){const p=await api(page,'previewAdminAccess',[userId,{kind:'modules',changes:[{moduleId,enabled}]}]);expect(p.blockers).toHaveLength(0);return api(page,'commitAdminModuleGrant',[userId,p.etag,[{moduleId,enabled}],p.previewToken]);}

test('FN-034 Notifications: UI read/unread, watermark, cancel/delete, SQL retention and foreign owner',async({page,browser},worker)=>{
 const admin=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport}),foreign=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL});
 try{const p=await admin.newPage();await login(p,'SuperAdmin');await page.goto('/');const me=await api(page,'getMe');const title=unique('inbox');const n=await publish(p,me.id,title);const before=sql('Notification',n.id)[0];expect(before.OwnerUserId.toLowerCase()).toBe(me.id.toLowerCase());
 await page.goto('/notifications');const row=page.locator('.notification-card').filter({has:page.getByRole('heading',{name:title,exact:true})});await expect(row).toBeVisible();
 const channels=(await api(page,'listNotifications')).items.find((i:any)=>i.id===n.id).deliveries;expect(channels.map((d:any)=>d.channel).sort()).toEqual(['BrowserPush','Email','InApp']);expect(channels.find((d:any)=>d.channel==='BrowserPush').state).toBe('PermissionUnavailable');
 await row.getByRole('button',{name:'Đánh dấu đã đọc',exact:true}).click();await expect.poll(()=>Boolean(sql('Notification',n.id)[0].ReadAt)).toBe(true);
 await row.getByRole('button',{name:'Đánh dấu chưa đọc',exact:true}).click();await expect.poll(()=>sql('Notification',n.id)[0].ReadAt).toBeNull();
 await page.getByRole('button',{name:'Đánh dấu tất cả đã đọc',exact:true}).click();await expect.poll(()=>Boolean(sql('Notification',n.id)[0].ReadAt)).toBe(true);
 const later=await publish(p,me.id,unique('after-watermark'));expect(sql('Notification',later.id)[0].ReadAt).toBeNull();await page.reload();
 await page.getByLabel('Chọn '+title,{exact:true}).check();await page.getByRole('button',{name:'Xóa mục đã chọn',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();expect(sql('Notification',n.id)[0].DeletedAt).toBeNull();
 await page.getByRole('button',{name:'Xóa mục đã chọn',exact:true}).click();await confirm(page,'Xóa mục đã chọn');await expect.poll(()=>Boolean(sql('Notification',n.id)[0].DeletedAt)).toBe(true);expect(sql('Notification',later.id)[0].DeletedAt).toBeNull();await page.reload();await expect(row).toHaveCount(0);
 const b=await foreign.newPage();await login(b,'UserB');expect((await api(b,'listNotifications')).items.some((i:any)=>i.id===later.id)).toBe(false);
 const item=(await api(page,'listNotifications')).items.find((i:any)=>i.id===later.id);const denied=await b.evaluate(async({id,etag})=>{const path='/src/api.ts',a=await import(path);try{await a.markNotificationRead(id,etag,true);return 200;}catch(e:any){return e.status;}},{id:later.id,etag:item.etag});expect(denied).toBe(404);expect(sql('Notification',later.id)[0].ReadAt).toBeNull();
 }finally{await admin.close();await foreign.close();}
});

test('FN-035 AdminReader: granted API metadata, denied admin screens, direct preview denied and SQL unchanged',async({browser},worker)=>{
 const context=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport});try{const p=await context.newPage();await login(p,'AdminReader');const users=await api(p,'listAdminUsers');expect(users.items.length).toBeGreaterThan(0);const target=users.items.find((u:any)=>u.email===account('Admin').email);expect(target).toBeTruthy();const before=operator('read-access',target.id);await p.goto('/admin/access');await expect(p.locator('#admin-role')).toHaveCount(0);await expect(p.locator('#admin-action')).toHaveCount(0);await expect(p.getByRole('button',{name:'Xem preview role',exact:true})).toHaveCount(0);
 const denied=await p.evaluate(async id=>{const path='/src/api.ts',a=await import(path);try{await a.previewAdminAccess(id,{kind:'permissions',changes:[{actionKey:'settings.preference.update',effect:'Allow'}]});return 200;}catch(e:any){return e.status;}},target.id);expect(denied).toBe(403);expect(operator('read-access',target.id)).toEqual(before);
 await p.goto('/admin/modules');await expect(p.getByRole('heading',{name:'Không có quyền truy cập quản trị',exact:true})).toBeVisible();await expect(p.getByRole('checkbox')).toHaveCount(0);await expect(p.getByRole('button',{name:/Xem lại thay đổi/})).toHaveCount(0);
 }finally{await context.close();}
});

test('FN-036 Action grants: UI Allow/Deny/Unset, Admin SELF rechecks and SQL preference ownership',async({browser},worker)=>{
 const context=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport}),actor=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport});let target:any,before:any;
 try{const p=await context.newPage();await login(p,'SuperAdmin');const users=await api(p,'listAdminUsers',[account('Admin').email]);target=users.items.find((u:any)=>u.email===account('Admin').email);before=await api(p,'getAdminUserAccess',[target.id]);await setGrant(p,target.id,'settings.preference.read','Allow');await setGrant(p,target.id,'settings.preference.update','Unset');const a=await actor.newPage();await login(a,'Admin');const me=await api(a,'getMe');await selectTarget(p,target.email);
 const key='settings.preference.update';
 for(const effect of ['Allow','Deny','Unset']){await p.locator('#admin-action').fill(key);await p.locator('#admin-effect').selectOption(effect);await p.getByRole('button',{name:'Xem preview quyền',exact:true}).click();await expect(p.getByRole('dialog')).toBeVisible();
  if(effect==='Allow'){const snapshot=operator('read-access',target.id);await p.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();expect(operator('read-access',target.id)).toEqual(snapshot);await p.getByRole('button',{name:'Xem preview quyền',exact:true}).click();}
  await confirm(p,'Xác nhận commit');await expect.poll(()=>operator('read-access',target.id).actionGrants.find((g:any)=>g.ActionKey===key)?.Effect??'Unset').toBe(effect);
  if(effect==='Allow'){await a.goto('/settings/profile');await a.locator('#theme-mode').selectOption('Dark');const response=a.waitForResponse(r=>r.url().endsWith('/api/v1/settings/preferences/theme')&&r.request().method()==='PUT');await a.getByRole('button',{name:'Lưu preferences',exact:true}).click();expect((await response).status()).toBe(200);const item=(await api(a,'listPreferences')).items.find((b:any)=>b.preferenceKey==='theme');expect(sql('Preference',item.id)[0].OwnerId.toLowerCase()).toBe(me.personalSpaceId.toLowerCase());expect(JSON.parse(sql('Preference',item.id)[0].ValueJson).mode).toBe('Dark');}
  else{const result=await a.evaluate(async()=>{const path='/src/api.ts',m=await import(path);const item=(await m.listPreferences()).items.find((i:any)=>i.preferenceKey==='theme');try{await m.updatePreference('theme',item?.etag??'*',{mode:'Light'});return 200;}catch(e:any){return e.status;}});expect(result).toBe(403);const item=(await api(a,'listPreferences')).items.find((i:any)=>i.preferenceKey==='theme');expect(JSON.parse(sql('Preference',item.id)[0].ValueJson).mode).toBe('Dark');}
 }
 }finally{if(target&&before){const p=context.pages()[0];for(const key of ['settings.preference.read','settings.preference.update'])await setGrant(p,target.id,key,before.actionGrants.find((g:any)=>g.actionKey===key)?.effect??'Unset');}await context.close();await actor.close();}
});

test('FN-037 User module grant: cancel/disable/re-enable Goals preserves SQL and blocks direct API',async({browser},worker)=>{
 const admin=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport}),owner=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport});let target:any,grant:any,dependent:any;
 try{const p=await admin.newPage();await login(p,'SuperAdmin');const u=await owner.newPage();await login(u,'UserB');target=await api(u,'getMe');const access=await api(p,'getAdminUserAccess',[target.id]);dependent=access.moduleGrants.find((g:any)=>g.code==='FX17');grant=access.moduleGrants.find((g:any)=>g.code==='FX16');expect(grant.enabled).toBe(true);const today=new Date().toISOString().slice(0,10);const created=await api(u,'createGoal',[unique('retained-goal'),'Real SQL prerequisite',today,null]);const goal=created.goal;const row=sql('Goal',goal.id)[0];await selectTarget(p,target.email);const box=p.getByRole('checkbox',{name:'FX16 module grant',exact:true});await box.click();await p.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();expect(operator('read-access',target.id).moduleGrants.find((g:any)=>g.Code==='FX16').Enabled).toBe(true);
 await box.click();await expect(p.getByRole('dialog').getByRole('button',{name:'Xác nhận commit',exact:true})).toBeDisabled();await expect(p.getByRole('dialog')).toContainText('FX17');await p.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();await p.getByRole('checkbox',{name:'FX17 module grant',exact:true}).click();await confirm(p,'Xác nhận commit');expect(operator('read-access',target.id).moduleGrants.find((g:any)=>g.Code==='FX17').Enabled).toBe(false);await box.click();await confirm(p,'Xác nhận commit');await expect.poll(()=>operator('read-access',target.id).moduleGrants.find((g:any)=>g.Code==='FX16').Enabled).toBe(false);expect(sql('Goal',goal.id)[0]).toEqual(row);await u.goto('/goals');await expect(u.getByRole('heading',{name:'Module chưa khả dụng',exact:true})).toBeVisible();const denied=await u.evaluate(async()=> (await fetch('/api/v1/goals')).status);expect(denied).toBe(409);
 await box.click();await confirm(p,'Xác nhận commit');await expect.poll(()=>operator('read-access',target.id).moduleGrants.find((g:any)=>g.Code==='FX16').Enabled).toBe(true);await u.reload();await expect(u.getByText(goal.title,{exact:true}).first()).toBeVisible();expect(sql('Goal',goal.id)[0]).toEqual(row);
 }finally{if(target&&grant){const p=admin.pages()[0],a=await api(p,'getAdminUserAccess',[target.id]);if(a.moduleGrants.find((g:any)=>g.code==='FX16').enabled!==grant.enabled)await setModules(p,target.id,grant.moduleId,grant.enabled);const current=await api(p,'getAdminUserAccess',[target.id]);if(dependent&&current.moduleGrants.find((g:any)=>g.code==='FX17').enabled!==dependent.enabled)await setModules(p,target.id,dependent.moduleId,dependent.enabled);}await admin.close();await owner.close();}
});

test('FN-038 Module policy: explicit registration default commit, existing user retained, paused preview blocked',async({page,browser},worker)=>{
 const context=await browser.newContext({baseURL:process.env.NEXORA_E2E_BASE_URL,viewport:worker.project.use.viewport});let before:any;
 try{const p=await context.newPage();await login(p,'SuperAdmin');before=(await api(p,'listAdminModules')).items.find((m:any)=>m.code==='FX32');await page.goto('/');const old=await api(page,'getMe');await p.goto('/admin/modules');const row=p.locator('.module-card').filter({has:p.getByText('FX32',{exact:true})});for(const enabled of [!before.registrationEnabled,before.registrationEnabled]){await row.getByLabel('Registration default',{exact:true}).setChecked(enabled);await row.getByRole('button',{name:'Xem lại thay đổi FX32',exact:true}).click();await confirm(p,'Xác nhận policy');await expect.poll(()=>operator('catalog').modules.find((m:any)=>m.Code==='FX32').RegistrationEnabled).toBe(enabled);expect((await api(page,'getMe')).modules.find((m:any)=>m.code==='FX32').enabled).toBe(old.modules.find((m:any)=>m.code==='FX32').enabled);}
 for(const code of ['FX30','FX34','FX35']){const r=p.locator('.module-card').filter({has:p.getByText(code,{exact:true})});const snapshot=operator('catalog').modules.find((m:any)=>m.Code===code);await r.getByLabel('System enabled',{exact:true}).check();await r.getByRole('button',{name:'Xem lại thay đổi '+code,exact:true}).click();await expect(p.getByRole('dialog').getByRole('button',{name:'Xác nhận policy',exact:true})).toBeDisabled();await p.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();expect(operator('catalog').modules.find((m:any)=>m.Code===code)).toEqual(snapshot);}
 }finally{if(before){const p=context.pages()[0],m=(await api(p,'listAdminModules')).items.find((m:any)=>m.code==='FX32');if(m.registrationEnabled!==before.registrationEnabled){const preview=await api(p,'previewModulePolicy',[m.id,{registrationEnabled:before.registrationEnabled}]);await api(p,'commitModulePolicy',[m.id,preview.etag,{registrationEnabled:before.registrationEnabled},preview.previewToken]);}}await context.close();}
});
