import {test,expect,api,sql,sourceTask,card,confirm,unique} from './fixtures';

test('FN-039 Planner: UI reorder, boundary controls, week projection and SQL source preservation',async({page})=>{
 await page.goto('/');const first=await sourceTask(page),second=await sourceTask(page);const before=[sql('Task',first.task.id),sql('Task',second.task.id)];await page.goto('/planner');const date=await page.locator('#planner-date').inputValue();
 const pins:any[]=[];for(const task of [first.task,second.task])pins.push(await api(page,'pinPlannerTask',[task.id,date,'Reorder prerequisite']));await page.reload();const row=(title:string)=>page.locator('.resource-card').filter({has:page.getByText(title,{exact:true})});
 await expect(row(second.task.title)).toBeVisible();await row(second.task.title).getByRole('button',{name:'↑',exact:true}).click();
 await expect.poll(async()=>{const plan=await api(page,'listPlanner',[date,date]);const relevant=plan.pins.filter((p:any)=>pins.some(i=>i.id===p.id));return relevant.map((p:any)=>p.id);}).toEqual([pins[1].id,pins[0].id]);
 const snapshot=pins.map(p=>sql('PlannerPin',p.id));await page.locator('#planner-view').selectOption('week');await expect(page.getByRole('heading',{name:'Weekly plan',exact:true})).toBeVisible();await expect(row(first.task.title)).toBeVisible();expect(pins.map(p=>sql('PlannerPin',p.id))).toEqual(snapshot);expect([sql('Task',first.task.id),sql('Task',second.task.id)]).toEqual(before);
 await page.locator('#planner-view').selectOption('day');await page.reload();const current=await api(page,'listPlanner',[date,date]);const ordered=current.pins;await expect(row(ordered[0].taskTitle).getByRole('button',{name:'↑',exact:true})).toBeDisabled();await expect(row(ordered.at(-1).taskTitle).getByRole('button',{name:'↓',exact:true})).toBeDisabled();
});

test('FN-040 Project: UI edit, cancel/confirm skip, terminal read-only and SQL reload',async({page})=>{
 await page.goto('/');const name=unique('skip-project'),start=new Date(Date.now()+86400000).toISOString(),end=new Date(Date.now()+172800000).toISOString();const item=await api(page,'createProject',[name,'Safe local prerequisite',start,end]);await page.goto('/modules/FX11');await card(page,name).getByRole('button',{name:'Sửa',exact:true}).click();await page.locator('#project-name').fill(name+'-edited');await page.locator('#project-description').fill('Tiếng Việt kiểm thử sửa');await page.getByRole('button',{name:'Lưu Project',exact:true}).click();await expect.poll(()=>sql('Project',item.id)[0].Name).toBe(name+'-edited');expect(sql('Project',item.id)[0].Description).toBe('Tiếng Việt kiểm thử sửa');
 const row=card(page,name+'-edited');await row.getByRole('button',{name:'Bỏ qua',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Hủy',exact:true}).click();expect(sql('Project',item.id)[0].Status).toBe('NotStarted');await row.getByRole('button',{name:'Bỏ qua',exact:true}).click();await page.getByRole('dialog').getByLabel('Lý do bỏ qua',{exact:true}).fill('Không tiếp tục dự án tổng hợp');await confirm(page,'Bỏ qua Project');await expect.poll(()=>sql('Project',item.id)[0].Status).toBe('Skipped');await page.reload();await expect(row.getByRole('button',{name:'Sửa',exact:true})).toBeDisabled();await expect(row.getByRole('button',{name:'Bỏ qua',exact:true})).toHaveCount(0);
});
