import { apiFetch, jsonMutationHeaders } from './api';
const root = '/api/v1/assets/digital';
export const digitalKinds = ['Domain', 'Hosting', 'Vps', 'Certificate', 'License', 'OnlineService'] as const;
export type DigitalMetadata = { title: string; kind: string; provider: string | null; expiresOn: string | null; cost: string | null; currency: string | null; renewalCycle: string | null; notes: string | null; details: Record<string, Record<string, string | number | boolean | string[] | null> | null> };
export type DigitalAsset = { id: string; metadata: DigitalMetadata; state: string; storedState: string; expirationBasis: string; timeZoneId: string; asciiName: string | null; unicodeName: string | null; etag: string; updatedAt: string };
export type DigitalOperation = 'cancel' | 'archive' | 'unarchive' | 'trash' | 'restore' | 'purge';
export type DigitalPreview = { itemId: string; etag: string; operation: DigitalOperation; referenceCount: number };
export type DigitalVersion = { id: string; versionNumber: number; actionKey: string; createdAt: string; reason: string | null; snapshot: { fields: { metadata: DigitalMetadata; storedState: string; preArchiveState: string | null; preTrashState: string | null; asciiName: string | null; unicodeName: string | null } } };
export type DigitalRenewal = { id: string; renewedOn: string; previousExpiry: string | null; newExpiry: string; amount: string | null; currency: string | null; notes: string | null; createdAt: string };
export type DigitalFilter = { state: string; kind: string; query: string; expiry: string; from: string; to: string };
export type DigitalHistoryFilter = { version: string; action: string; from: string; to: string };
export const digitalCapabilities = () => apiFetch<Record<string, boolean>>(root + '/capabilities');
export const digitalGet = (id: string) => apiFetch<DigitalAsset>(root + '/' + encodeURIComponent(id));
const params = (values: Record<string, string>, cursor?: string) => { const p = new URLSearchParams(); for (const [key, value] of Object.entries(values)) if (value) p.set(key, value); if (cursor) p.set('cursor', cursor); return '?' + p; };
export const digitalList = (filters: DigitalFilter, cursor?: string) => apiFetch<{ items: DigitalAsset[]; nextCursor: string | null }>(root + params(filters, cursor));
export const digitalSave = (metadata: DigitalMetadata, state: string, confirmTypeChange: boolean, key: string, item?: DigitalAsset) => apiFetch<{ itemId: string; etag: string }>(root + (item ? '/' + item.id : ''), { method: item ? 'PUT' : 'POST', headers: jsonMutationHeaders(key, item ? { 'If-Match': item.etag } : {}), body: JSON.stringify(item ? { metadata, confirmTypeChange } : { metadata, state }) });
export const digitalRecordRenewal = (item: DigitalAsset, body: { renewedOn: string; newExpiry: string; amount: string | null; currency: string | null; notes: string | null; confirm: boolean }, key: string) => apiFetch<{ itemId: string; etag: string }>(root + '/' + item.id + '/record-renewal', { method: 'POST', headers: jsonMutationHeaders(key, { 'If-Match': item.etag }), body: JSON.stringify(body) });
export const digitalPreview = (item: DigitalAsset, operation: DigitalOperation) => apiFetch<DigitalPreview>(root + '/' + item.id + '/preview-' + operation, { method: 'POST', headers: jsonMutationHeaders(crypto.randomUUID()) });
export const digitalTransition = (preview: DigitalPreview, key: string) => apiFetch<{ itemId: string; etag: string | null }>(root + '/' + preview.itemId + '/' + preview.operation, { method: 'POST', headers: jsonMutationHeaders(key, { 'If-Match': preview.etag }), body: JSON.stringify({ confirm: true }) });
export const digitalHistory = (id: string, filters: DigitalHistoryFilter, cursor?: string) => apiFetch<{ items: DigitalVersion[]; nextCursor: string | null }>(root + '/' + id + '/history' + params(filters, cursor));
export const digitalRenewals = (id: string, cursor?: string) => apiFetch<{ items: DigitalRenewal[]; nextCursor: string | null }>(root + '/' + id + '/renewals' + params({}, cursor));
